{{- if (eq (.Values.replicaCount | toString) "0") }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "snipeit.fullname" . }}
  labels:
    app: {{ include "snipeit.name" . }}
    chart: {{ include "snipeit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "snipeit.name" . }}
      release: {{ .Release.Name }}
  maxUnavailable: {{ if .Values.maxUnavailable }}{{ .Values.maxUnavailable }}{{- else }}{{ ceil (div .Values.replicaCount 2) }}{{- end }}
{{- end }}
