apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "flow.fullname" . }}
  labels:
    app: {{ template "flow.name" . }}
    chart: {{ template "flow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ tpl (.Files.Glob "config/*").AsConfig . | nindent 2 }}
