{{- if .Values.workers -}}
{{- $root := . -}}
{{- range .Values.workers }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "flow.fullname" $root }}-{{ .name }}
  labels:
    app: {{ template "flow.name" $root }}
    component: worker
    chart: {{ template "flow.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  replicas: {{ .replicaCount | default 1 }}
  revisionHistoryLimit: {{ .revisionHistoryLimit | default 0 }}
  selector:
    matchLabels:
      app: {{ template "flow.name" $root }}
      component: worker
      release: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "flow.name" $root }}
        component: worker
        release: {{ $root.Release.Name }}
      annotations:
        {{- include "flow.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: {{ $root.Chart.Name }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          command:
          {{- range .command }}
            - {{ . | quote }}
          {{- end }}
          env:
            - name: FLOW_CONTEXT
              value: Production
            - name: FLOW_REWRITEURLS
              value: "1"
          envFrom:
            - secretRef:
                name: {{ template "flow.fullname" . }}
        {{- with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/Configuration/Production
      volumes:
        - name: config
          configMap:
            name: {{ template "flow.fullname" . }}
{{- end }}
{{- end -}}