kind: Secret
apiVersion: v1
metadata:
  name: {{ template "flow.fullname" . }}
  labels:
    app: {{ template "flow.name" . }}
    component: app
    chart: {{ template "flow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  DB_USER: {{ .Values.mariadb.mariadbUser | b64enc }}
  DB_PASS: {{ .Values.mariadb.mariadbPassword | b64enc }}
