apiVersion: v1
kind: Secret
metadata:
  name: {{ template "graylog.fullname" . }}
  labels:
    app: {{ template "graylog.name" . }}
    chart: {{ template "graylog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  GRAYLOG_PASSWORD_SECRET: {{ randAlphaNum 16 | b64enc }}
  GRAYLOG_ROOT_PASSWORD_SHA2: {{ .Values.adminPassword | sha256sum | b64enc }}
