apiVersion: v1
kind: Service
metadata:
  name: {{ template "graylog.fullname" . }}
  labels:
    app: {{ template "graylog.name" . }}
    chart: {{ template "graylog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ toYaml .Values.service.input.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.input.type }}
  ports:
  {{- range $port := .Values.service.input.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      protocol: {{ $port.protocol }}
  {{- end }}
  selector:
    app: {{ template "graylog.name" . }}
    release: {{ .Release.Name }}
