apiVersion: v1
kind: Service
metadata:
  name: {{ template "graylog.fullname" . }}-web
  labels:
    app: {{ template "graylog.name" . }}
    chart: {{ template "graylog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ toYaml .Values.service.web.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - name: http
      port: 9000
  selector:
    app: {{ template "graylog.name" . }}
    release: {{ .Release.Name }}
