apiVersion: v1
kind: Service
metadata:
  name: {{ include "fop.fullname" . }}
  labels:
    {{ include "fop.labels" . | indent 4 | trim }}
{{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 | trim }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 9999
      protocol: TCP
  selector:
    {{ include "fop.selector" . | indent 4 | trim }}
