{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stackdriver-prometheus.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "stackdriver-prometheus.name" . }}
    helm.sh/chart: {{ include "stackdriver-prometheus.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
