{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "promtail.serviceAccountName" . }}
  labels:
    {{ include "promtail.labels" . | indent 4 | trim }}
{{- end }}
