dependencies:
- name: elasticsearch
  version: ^1.0.0
  repository: https://storage.googleapis.com/t3n-helm-charts/
- name: mongodb
  version: ^1.0.0
  repository: https://storage.googleapis.com/t3n-helm-charts/
