revisionHistoryLimit: 0

image:
  repository: graylog2/server
  tag: 2.4.3-3
  pullPolicy: IfNotPresent

service:
  web:
    type: ClusterIP
    annotations: {}
  input:
    type: ClusterIP
    annotations: {}
    ports:
      - name: gelf-udp
        port: 12201
        protocol: UDP

persistence:
  enabled: true
  annotations: {}
    # volume.beta.kubernetes.io/storage-class: "hostpath-provisioner"
  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
    - graylog.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

adminPassword: changeme

extraEnv:
  GRAYLOG_ROTATION_STRATEGY: time
  GRAYLOG_ELASTICSEARCH_MAX_TIME_PER_INDEX: "1d"
  GRAYLOG_ELASTICSEARCH_MAX_NUMBER_OF_INDICES: "10"
  GRAYLOG_ELASTICSEARCH_INDEX_PREFIX: "graylog"
  GRAYLOG_ELASTICSEARCH_SHARDS: "1"

securityContext:
    enabled: true
    fsGroup: 1100
    runAsUser: 1100

#
# Elasticsearch Chart Settings
#

elasticsearch:
  image:
    tag: 5.3.3
  extraEnv:
    "discovery.type": ""
    "http.host": "0.0.0.0"
    "transport.host": "127.0.0.1"
    "bootstrap.memory_lock": "true"
    "xpack.security.enabled": "false"
