{{- if ne (index .Values.cloudsql.instances 0).instance "instance" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- if eq .Values.replicaCount 1.0 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
{{- end }}
  selector:
    matchLabels:
      {{ include "cloudsql-proxy.selector" . | indent 6 | trim }}
  template:
    metadata:
      labels:
        {{ include "cloudsql-proxy.selector" . | indent 8 | trim }}
    spec:
      serviceAccountName: {{ include "cloudsql-proxy.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /cloud_sql_proxy
            - --dir=/cloudsql
            - -instances={{- range .Values.cloudsql.instances -}}
                            {{ .project }}:{{ .region }}:{{ .instance }}=tcp:0.0.0.0:{{ .port }},
                         {{- end }}
          {{- if .Values.serviceAccountKey }}
            - -credential_file=/secrets/cloudsql/credentials.json
          {{- end }}
          ports:
          {{- range .Values.cloudsql.instances }}
            - name: {{ .instanceShortName | default (.instance | trunc 15) }}
              containerPort: {{ .port }}
          {{- end }}
        {{- with .Values.resources }}
          resources:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
          volumeMounts:
          {{- if .Values.serviceAccountKey }}
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
          {{- end }}
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
      {{- if .Values.serviceAccountKey }}
        - name: cloudsql-oauth-credentials
          secret:
            secretName: {{ include "cloudsql-proxy.fullname" . }}
      {{- end }}
        - name: cloudsql
          emptyDir: {}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
