{{- if ne (index .Values.cloudsql.instances 0).instance "instance" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudsql-proxy.name" . }}
    helm.sh/chart: {{ include "cloudsql-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- if eq .Values.replicaCount 1.0 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudsql-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cloudsql-proxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cloudsql-proxy.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /cloud_sql_proxy
            - --dir=/cloudsql
            - -instances={{- range .Values.cloudsql.instances -}}
                            {{ .project }}:{{ .region }}:{{ .instance }}=tcp:0.0.0.0:{{ .port }},
                         {{- end }}
          {{- if .Values.serviceAccountKey }}
            - -credential_file=/secrets/cloudsql/credentials.json
          {{- end }}
          ports:
          {{- range .Values.cloudsql.instances }}
            - name: {{ .instanceShortName | default (.instance | trunc 15) }}
              containerPort: {{ .port }}
          {{- end }}
          volumeMounts:
          {{- if .Values.serviceAccountKey }}
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
          {{- end }}
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
      {{- if .Values.serviceAccountKey }}
        - name: cloudsql-oauth-credentials
          secret:
            secretName: {{ include "cloudsql-proxy.fullname" . }}
      {{- end }}
        - name: cloudsql
          emptyDir: {}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
