{{- if gt .Values.replicaCount 1.0 -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudsql-proxy.name" . }}
    helm.sh/chart: {{ include "cloudsql-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudsql-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  maxUnavailable: {{ if .Values.maxUnavailable }}{{ .Values.maxUnavailable }}{{- else }}{{ ceil (div .Values.replicaCount 2) }}{{- end }}
{{- end -}}
