{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudsql-proxy.name" . }}
    helm.sh/chart: {{ include "cloudsql-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cloudsql-proxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudsql-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
