{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cloudsql-proxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudsql-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
