{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
{{- end -}}
