{{- if .Values.serviceAccountKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudsql-proxy.name" . }}
    helm.sh/chart: {{ include "cloudsql-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  credentials.json: |-
    {{ .Values.serviceAccountKey }}
{{- end -}}
