{{- if .Values.serviceAccountKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
type: Opaque
data:
  credentials.json: |-
    {{ .Values.serviceAccountKey }}
{{- end -}}
