{{- if ne (index .Values.cloudsql.instances 0).instance "instance" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
{{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
{{- end }}
  ports:
{{- range .Values.cloudsql.instances }}
  - name: {{ .instance }}
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ .instanceShortName | default (.instance | trunc 15) }}
{{- end }}
  selector:
    {{ include "cloudsql-proxy.selector" . | indent 4 | trim }}
{{- end -}}
