{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudsql-proxy.serviceAccountName" . }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
{{- end -}}
