apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}-udp
  labels: {{- include "pi-hole.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- with .Values.ports }}
  ports:
  {{- range $key, $value := . }}
  {{- if (eq (toString $value.protocol) "UDP") }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $key }}
      protocol: UDP
  {{- end }}
  {{- end }}
{{- end }}
  selector: {{- include "pi-hole.selector" . | nindent 4 }}
