{{- if not .Values.existingConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gtmetrix-bq.fullname" . }}
  labels: {{- include "gtmetrix-bq.labels" . | nindent 4 }}
data:
  config.yaml: {{- toYaml .Values.config | nindent 4 }}
{{- end }}
