apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "gtmetrix-bq.fullname" . }}
  labels: {{- include "gtmetrix-bq.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
{{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
{{- end }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "gtmetrix-bq.fullname" . }}
          labels: {{- include "gtmetrix-bq.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
        {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
          {{- range . }}
            - name: {{ . }}
          {{- end }}
        {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
              {{- range .Values.command }}
                - {{ . | quote }}
              {{- end }}
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "/app/credentials.json"
            {{- with .Values.extraEnvs }}
              {{- range $key, $value := . }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
              {{- end }}
            {{- end }}
            {{- if or .Values.secretEnvs .Values.existingEnvsSecret }}
              envFrom:
                - secretRef:
                    name: {{ if .Values.existingEnvsSecret }}{{ .Values.existingEnvsSecret }}{{ else }}{{ include "gtmetrix-bq.fullname" . }}-envs{{ end }}
            {{- end }}
            {{- with .Values.resources }}
              resources:
                {{ toYaml . | indent 16 | trim }}
            {{- end }}
              volumeMounts:
                - name: config
                  mountPath: /app/config.yaml
                  subPath: config.yaml
                - name: credentials
                  mountPath: /app/credentials.json
                  subPath: credentials.json
          volumes:
            - name: config
              configMap:
                name: {{ if .Values.existingConfigMap }}{{ .Values.existingConfigMap }}{{ else }}{{ include "gtmetrix-bq.fullname" . }}{{ end }}
            - name: credentials
              secret:
                secretName: {{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ include "gtmetrix-bq.fullname" . }}{{ end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
