kind: Secret
apiVersion: v1
metadata:
  name: {{ include "gtmetrix-bq.fullname" . }}
  labels: {{- include "gtmetrix-bq.labels" . | nindent 4 }}
data:
  credentials.json:
    {{ toYaml .Values.credentials | indent 4 | trim }}
