{{- if and .Values.secretEnvs (not .Values.existingEnvsSecret) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "gtmetrix-bq.fullname" . }}-envs
  labels: {{- include "gtmetrix-bq.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretEnvs }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
