{{- if .Values.sanitize.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql-backup.fullname" . }}-sanitize
  labels:
    {{ include "mysql-backup.labels" . | indent 4 | trim }}
data:
  sanitize.sql: |-
    {{- range .Values.sanitize.sql }}
    {{ . }}
    {{- end }}
{{- end -}}
