apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql-backup.fullname" . }}
  labels:
    {{ include "mysql-backup.labels" . | indent 4 | trim }}
data:
{{ tpl (.Files.Glob "scripts/*").AsConfig . | indent 2 }}
