apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql-backup.fullname" . }}
  labels:
    app: {{ include "mysql-backup.fullname" . }}
    chart: {{ include "mysql-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ tpl (.Files.Glob "scripts/*").AsConfig . | indent 2 }}
