kind: Secret
apiVersion: v1
metadata:
  name: {{ template "mysql-backup.fullname" . }}-gcs
  labels:
    {{ include "mysql-backup.labels" . | indent 4 | trim }}
type: Opaque
data:
  key.json: |-
    {{ .Values.gcs.serviceAccountKey }}
