kind: Secret
apiVersion: v1
metadata:
  name: {{ template "mysql-backup.fullname" . }}-mysql
  labels:
    app: {{ template "mysql-backup.fullname" . }}
    chart: {{ template "mysql-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASS: {{ .Values.database.pass | b64enc | quote }}
