kind: Secret
apiVersion: v1
metadata:
  name: {{ template "mysql-backup.fullname" . }}-mysql
  labels:
    {{ include "mysql-backup.labels" . | indent 4 | trim }}
data:
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASS: {{ .Values.database.pass | b64enc | quote }}
