kind: Secret
apiVersion: v1
metadata:
  name: {{ template "mysql-backup.fullname" . }}-gcs
  labels:
    app: {{ template "mysql-backup.fullname" . }}
    chart: {{ template "mysql-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  key.json: |-
    {{ .Values.gcs.serviceAccountKey }}
